/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Controller;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;

public class View extends javax.swing.JFrame {

    Controller controller;
    DefaultTableModel modelFoods = new DefaultTableModel();
    DefaultTableModel modelConsumedFoods = new DefaultTableModel();
    
    /**
     * Constructor that instantiate the controller,
     * gets the foods and puts them into the foods and consumed foods tables,
     * gets the current date and sets up the JFrame
     */
    public View() {
        super("Diet Manager");

        controller = new Controller();

        try {
            UIManager.setLookAndFeel("com.formdev.flatlaf.FlatDarculaLaf");
        } catch (Exception e) {
            e.printStackTrace();
        }

        initComponents();

        ArrayList<String> foods = controller.getAllFoods();

        Date date = Calendar.getInstance().getTime();
        DateFormat df = new SimpleDateFormat("dd");
        jtfDay.setText(df.format(date));
        df = new SimpleDateFormat("MM");
        jtfMonth.setText(df.format(date));
        df = new SimpleDateFormat("yyyy");
        jtfYear.setText(df.format(date));

        this.setVisible(true);

        modelFoods.addColumn("Food Name");
        modelConsumedFoods.addColumn("Consumed Foods");
        displayFoodItems(foods);
        displayIntakeInfo();
    }

    /**
     * Adds a Model.ModelFood.BasicFood or Model.ModelFood.Recipe to UTIL.Foods
     */
    public void addFood(char type, String data) {
        controller.addFood(type, data);
    }

    /**
     * Displays all of the food items into the food table
     */
    public void displayFoodItems(ArrayList<String> foodNames) {
        for (String name : foodNames) {
            String[] data = {name};
            modelFoods.addRow(data);
            jcbConsumed.addItem(name);
            jcbComponent.addItem(name);
        }
    }

    /**
     * Gets info about a Model.ModelFood.BasicFood or Model.ModelFood.Recipe
     */
    public ArrayList getFoodInfo(String name) {

        return controller.getFoodInfo(name);
    }


    /**
     * Adds a Model.ModelFood.BasicFood or Model.ModelFood.Recipe to the
     *
     * @param day desired day
     * @param name food name
     */
    public void addToIntake(String day, String name) {
        controller.addToIntake(day, name);
    }

    /**
     * Gets the info for a specific intake based on the entered date
     */
    public void displayIntakeInfo() {
        ArrayList<Object> info = controller.getIntakeInfo(getDateInput());

        jtfCalorieLimit.setText((String) info.get(0));
        jtfWeight.setText((String) info.get(1));

        jtfCurrCalories.setText((String) info.get(2)); // updates calories
        jtfCurrFat.setText((String) info.get(3)); // updates fat
        jtfCurrProtein.setText((String) info.get(4)); // updates protein
        jtfCurrCarb.setText((String) info.get(5)); // updates carb

        int rowNum = modelConsumedFoods.getRowCount();
        for (int i = rowNum - 1; i >= 0; i--) {
            modelConsumedFoods.removeRow(i);
        }

        for (String name : (ArrayList<String>) info.get(6)) {
            String[] data = {name};
            modelConsumedFoods.addRow(data);
        }

    }
    
    /**
     * Gets the entered date
     * @return the date in a string format
     */
    public String getDateInput() {
        String day = jtfDay.getText();
        String month = jtfMonth.getText();
        String year = jtfYear.getText();

        return year + "/" + month + "/" + day;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jdAddBasicFood = new javax.swing.JDialog();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jtfProtein = new javax.swing.JTextField();
        jtfFoodName = new javax.swing.JTextField();
        jtfCalories = new javax.swing.JTextField();
        jtfFat = new javax.swing.JTextField();
        jtfCarb = new javax.swing.JTextField();
        jbCancel = new javax.swing.JButton();
        jbSave = new javax.swing.JButton();
        jdAddRecipe = new javax.swing.JDialog();
        jLabel18 = new javax.swing.JLabel();
        jtfRecipeName = new javax.swing.JTextField();
        jbAddComponent = new javax.swing.JButton();
        jbCancleRecipe = new javax.swing.JButton();
        jbSaveRecipe = new javax.swing.JButton();
        jtfComponentCount = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel22 = new javax.swing.JLabel();
        jcbComponent = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtFoods = new javax.swing.JTable();
        jbAddRecipe = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtfDay = new javax.swing.JTextField();
        jtfYear = new javax.swing.JTextField();
        jtfMonth = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfWeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtfCalorieLimit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsumedFoods = new javax.swing.JTable();
        jbAddConsumed = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtfCurrCalories = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jbDisplayIntake = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jcbConsumed = new javax.swing.JComboBox<>();
        jtfCurrProtein = new javax.swing.JTextField();
        jtfCurrCarb = new javax.swing.JTextField();
        jtfCurrFat = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jbSaveIntake = new javax.swing.JButton();

        jdAddBasicFood.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setText("Food name:");
        jdAddBasicFood.getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 80, 30));

        jLabel9.setText("Calories: ");
        jdAddBasicFood.getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 70, 30));

        jLabel11.setText("Fat");
        jdAddBasicFood.getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 70, 30));

        jLabel12.setText("Carb:");
        jdAddBasicFood.getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel13.setText("Protein:");
        jdAddBasicFood.getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        jtfProtein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfProteinActionPerformed(evt);
            }
        });
        jdAddBasicFood.getContentPane().add(jtfProtein, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, 20));

        jtfFoodName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfFoodNameActionPerformed(evt);
            }
        });
        jdAddBasicFood.getContentPane().add(jtfFoodName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 140, 20));
        jdAddBasicFood.getContentPane().add(jtfCalories, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 140, 20));
        jdAddBasicFood.getContentPane().add(jtfFat, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 140, 20));
        jdAddBasicFood.getContentPane().add(jtfCarb, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, 20));

        jbCancel.setText("Cancle");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jdAddBasicFood.getContentPane().add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, -1, -1));

        jbSave.setText("Save");
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });
        jdAddBasicFood.getContentPane().add(jbSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, -1, -1));

        jLabel18.setText("Recipe Name");

        jbAddComponent.setText("Add");
        jbAddComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddComponentActionPerformed(evt);
            }
        });

        jbCancleRecipe.setText("Cancel");
        jbCancleRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancleRecipeActionPerformed(evt);
            }
        });

        jbSaveRecipe.setText("Save");
        jbSaveRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveRecipeActionPerformed(evt);
            }
        });

        jLabel19.setText("Componenet Count");

        jLabel20.setText("Componenet Name");

        jLabel21.setText("Add new componet to the recipe");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Count"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel22.setText("Current components");

        jcbComponent.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select component" }));
        jcbComponent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbComponentActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jdAddRecipeLayout = new javax.swing.GroupLayout(jdAddRecipe.getContentPane());
        jdAddRecipe.getContentPane().setLayout(jdAddRecipeLayout);
        jdAddRecipeLayout.setHorizontalGroup(
            jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddRecipeLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addGroup(jdAddRecipeLayout.createSequentialGroup()
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jbSaveRecipe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jbAddComponent)
                        .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jdAddRecipeLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(50, 50, 50)
                                .addComponent(jtfComponentCount))
                            .addGroup(jdAddRecipeLayout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jcbComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(2, 2, 2)))
                        .addComponent(jbCancleRecipe)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jdAddRecipeLayout.setVerticalGroup(
            jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jdAddRecipeLayout.createSequentialGroup()
                .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jdAddRecipeLayout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(jLabel21)
                            .addGap(19, 19, 19)
                            .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel20)
                                .addComponent(jcbComponent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(25, 25, 25)
                            .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel19)
                                .addComponent(jtfComponentCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(38, 38, 38)
                            .addComponent(jbAddComponent)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbCancleRecipe))
                        .addGroup(jdAddRecipeLayout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(jdAddRecipeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jtfRecipeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel18))
                            .addGap(31, 31, 31)
                            .addComponent(jLabel22)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(30, 30, 30)
                            .addComponent(jbSaveRecipe))))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel2.setText("Foods & Recepies");

        jButton1.setText("Add Food");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remove Food");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jtFoods.setModel(modelFoods);
        jtFoods.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtFoods);

        jbAddRecipe.setText("Add Recipe");
        jbAddRecipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddRecipeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbAddRecipe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(60, 60, 60)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbAddRecipe)
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel1.setText("Daily Intake");

        jLabel3.setText("Select the Date");

        jLabel4.setText("day / month / year");

        jtfDay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDayActionPerformed(evt);
            }
        });

        jtfMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfMonthActionPerformed(evt);
            }
        });

        jLabel5.setText("Weight");

        jtfWeight.setText("68");
        jtfWeight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfWeightActionPerformed(evt);
            }
        });

        jLabel6.setText("Calorie Limit");

        jtfCalorieLimit.setText("2000");

        jLabel7.setText("Consumed Foods");

        jtConsumedFoods.setModel(modelConsumedFoods);
        jScrollPane1.setViewportView(jtConsumedFoods);

        jbAddConsumed.setText("Add");
        jbAddConsumed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAddConsumedActionPerformed(evt);
            }
        });

        jLabel8.setText("Calories");

        jtfCurrCalories.setText("0");
        jtfCurrCalories.setEnabled(false);
        jtfCurrCalories.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrCaloriesActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jbDisplayIntake.setText("Display");
        jbDisplayIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDisplayIntakeActionPerformed(evt);
            }
        });

        jButton5.setText("Set Weight");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Set Limit");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jcbConsumed.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Consumed Food" }));
        jcbConsumed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbConsumedActionPerformed(evt);
            }
        });

        jtfCurrProtein.setText("0");
        jtfCurrProtein.setEnabled(false);
        jtfCurrProtein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCurrProteinActionPerformed(evt);
            }
        });

        jtfCurrCarb.setText("0");
        jtfCurrCarb.setEnabled(false);

        jtfCurrFat.setText("0");
        jtfCurrFat.setEnabled(false);

        jLabel14.setText("Fat");

        jLabel15.setText("Current nutrients: ");

        jLabel16.setText("Protein");

        jLabel17.setText("Carb");

        jbSaveIntake.setText("Save");
        jbSaveIntake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveIntakeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jtfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbDisplayIntake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(213, 213, 213))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel7)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jtfCalorieLimit, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(17, 17, 17)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButton5)
                                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(8, 8, 8))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(93, 93, 93)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jbAddConsumed, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jbSaveIntake))
                                            .addComponent(jcbConsumed, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jtfCurrProtein, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jtfCurrCalories, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jtfCurrFat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jtfCurrCarb, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))))))))
                        .addContainerGap(167, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtfYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbDisplayIntake)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jtfCurrCalories, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtfCurrFat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jtfCurrProtein, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(12, 12, 12)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jtfCurrCarb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel5)
                        .addGap(27, 27, 27)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton5)
                            .addComponent(jtfWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jtfCalorieLimit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jcbConsumed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jbAddConsumed)
                            .addComponent(jbSaveIntake)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
            .addComponent(jSeparator1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
    
    /**
     * Opens the dialog for entering a new food item
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jdAddBasicFood.setVisible(true);
        jdAddBasicFood.setSize(450, 300);
        jdAddBasicFood.setLocation(1000, 100);
    }//GEN-LAST:event_jButton1ActionPerformed
    
    /**
     * Adds a food to an intake based on the entered date
     * @param evt 
     */
    private void jbAddConsumedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddConsumedActionPerformed
        String date = getDateInput();
        String foodName = (String) jcbConsumed.getSelectedItem();

        addToIntake(date, foodName);
        displayIntakeInfo();
    }//GEN-LAST:event_jbAddConsumedActionPerformed

    private void jtfMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfMonthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfMonthActionPerformed

    private void jtfDayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDayActionPerformed

    private void jtfWeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfWeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfWeightActionPerformed

    /**
     * Displays the data for selected date Navigates through dailyIntake
     */
    private void jbDisplayIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDisplayIntakeActionPerformed
        // TODO add your handling code here:
        displayIntakeInfo();

    }//GEN-LAST:event_jbDisplayIntakeActionPerformed

    private void jtfCurrCaloriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrCaloriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrCaloriesActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * Saves the entered food into the food list
     * @param evt 
     */
    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        // TODO add your handling code here:
        String foodName = jtfFoodName.getText();
        String carbs = jtfCarb.getText();
        String fat = jtfFat.getText();
        String protein = jtfProtein.getText();
        String calories = jtfCalories.getText();

        // violates dry
        jtfFat.getText().isEmpty();
        if (jtfFat.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to enter a number for fat");
            return;
        }

        if (jtfCarb.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to enter a number for carb");
            return;
        }

        if (jtfProtein.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to enter a number for protein");
            return;
        }

        if (jtfCalories.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "You need to enter a number for calories");
            return;
        }

        try {
            Double.parseDouble(carbs);
            Double.parseDouble(fat);
            Double.parseDouble(protein);
            Double.parseDouble(calories);

            String data = String.format("%s, %s, %s, %s, %s", foodName, calories, fat, carbs, protein);

            // Cends data to ResourceHandler
            controller.addFood('b', data);

            modelFoods.getDataVector().removeAllElements();

            jcbConsumed.removeAllItems();
            jcbComponent.removeAllItems();
            displayFoodItems(controller.getAllFoods());

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You need to enter a nuber for calories, fat, protein and carbs");

        }

        jtfFoodName.setText("");
        jtfCarb.setText("");
        jtfFat.setText("");
        jtfProtein.setText("");
        jtfCalories.setText("");
        jdAddBasicFood.setVisible(false);

    }//GEN-LAST:event_jbSaveActionPerformed
    
    /**
     * Clears the input fields and closes the add food dialog
     * @param evt 
     */
    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        jtfFoodName.setText("");
        jtfCarb.setText("");
        jtfFat.setText("");
        jtfProtein.setText("");
        jtfCalories.setText("");
        jdAddBasicFood.setVisible(false);
    }//GEN-LAST:event_jbCancelActionPerformed

    private void jtfFoodNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfFoodNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfFoodNameActionPerformed

    private void jtfProteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfProteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfProteinActionPerformed

    private void jtfCurrProteinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCurrProteinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCurrProteinActionPerformed
    
    /**
     * Opens the add recipe dialog
     * @param evt 
     */
    private void jbAddRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddRecipeActionPerformed

        jdAddRecipe.setVisible(true);
        
        jdAddRecipe.setSize(750, 380);
        jdAddRecipe.setLocation(100, 100);
    }//GEN-LAST:event_jbAddRecipeActionPerformed

    /**
     * Saves the new entered recipe
     * @param evt 
     */
    private void jbSaveRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveRecipeActionPerformed

        String recipeName = jtfRecipeName.getText();

        if (recipeName.equals("")) {
            JOptionPane.showMessageDialog(null, "Plese enter a recipe name");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        // Map<String, Double> map = new HashMap<>();
        StringBuilder sb = new StringBuilder(String.format("%s,", recipeName));

        for (int count = 0; count < model.getRowCount(); count++) {
            String cName = model.getValueAt(count, 0).toString();
            Double cCount = Double.parseDouble(model.getValueAt(count, 1).toString());
            sb.append(String.format("%s, %s,", cName, cCount));
        }
        controller.addFood('r', sb.toString());

        modelFoods.getDataVector().removeAllElements();

        jcbConsumed.removeAllItems();
        displayFoodItems(controller.getAllFoods());
        jdAddRecipe.setVisible(false); // hides addRecipe dialog

        // resets add component fields
        jtfComponentCount.setText("");
        jcbComponent.setSelectedIndex(0);

        // resets recipe name and teble
        jtfRecipeName.setText("");
        model.getDataVector().removeAllElements();
    }//GEN-LAST:event_jbSaveRecipeActionPerformed
    
    /**
     * Adds a component to the recipe
     * @param evt 
     */
    private void jbAddComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAddComponentActionPerformed

        double componenetCount = 0;
        try {
            componenetCount = Double.parseDouble(jtfComponentCount.getText());;
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "You need to enter a nuber for componenet count");
        }

        // check if name exists in the foods
        String componenetName = jcbComponent.getSelectedItem().toString();

        String[] row = {componenetName, String.valueOf(componenetCount)};

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(row);

        jtfComponentCount.setText("");
        jcbComponent.setSelectedIndex(0);
    }//GEN-LAST:event_jbAddComponentActionPerformed

    private void jcbConsumedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbConsumedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbConsumedActionPerformed

    private void jcbComponentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbComponentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbComponentActionPerformed
    
    /**
     * Closes the add recipe dialog
     * @param evt 
     */
    private void jbCancleRecipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancleRecipeActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        jdAddRecipe.setVisible(false); // hides addRecipe dialog

        // resets add component fields
        jtfComponentCount.setText("");
        jcbComponent.setSelectedIndex(0);

        // resets recipe name and teble
        jtfRecipeName.setText("");
        model.getDataVector().removeAllElements();

    }//GEN-LAST:event_jbCancleRecipeActionPerformed

    /**
     * Saves data for the current intake into the log file
     * @param evt click
     */
    private void jbSaveIntakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveIntakeActionPerformed

        controller.saveIntake(getDateInput());

    }//GEN-LAST:event_jbSaveIntakeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbAddComponent;
    private javax.swing.JButton jbAddConsumed;
    private javax.swing.JButton jbAddRecipe;
    private javax.swing.JButton jbCancel;
    private javax.swing.JButton jbCancleRecipe;
    private javax.swing.JButton jbDisplayIntake;
    private javax.swing.JButton jbSave;
    private javax.swing.JButton jbSaveIntake;
    private javax.swing.JButton jbSaveRecipe;
    private javax.swing.JComboBox<String> jcbComponent;
    private javax.swing.JComboBox<String> jcbConsumed;
    private javax.swing.JDialog jdAddBasicFood;
    private javax.swing.JDialog jdAddRecipe;
    private javax.swing.JTable jtConsumedFoods;
    private javax.swing.JTable jtFoods;
    private javax.swing.JTextField jtfCalorieLimit;
    private javax.swing.JTextField jtfCalories;
    private javax.swing.JTextField jtfCarb;
    private javax.swing.JTextField jtfComponentCount;
    private javax.swing.JTextField jtfCurrCalories;
    private javax.swing.JTextField jtfCurrCarb;
    private javax.swing.JTextField jtfCurrFat;
    private javax.swing.JTextField jtfCurrProtein;
    private javax.swing.JTextField jtfDay;
    private javax.swing.JTextField jtfFat;
    private javax.swing.JTextField jtfFoodName;
    private javax.swing.JTextField jtfMonth;
    private javax.swing.JTextField jtfProtein;
    private javax.swing.JTextField jtfRecipeName;
    private javax.swing.JTextField jtfWeight;
    private javax.swing.JTextField jtfYear;
    // End of variables declaration//GEN-END:variables
}
